@startuml
hide footbox

actor "Usuário\n(Gerente ou Colaborador)" as usuario

usuario -> InterfaceClientes: 1:acessarAbaClientes()
activate InterfaceClientes

InterfaceClientes --> usuario: 1.1:exibirClientes()

usuario -> InterfaceClientes: 2:novoCliente()
InterfaceClientes --> usuario: 2.1:exibirFormularioCadastro()

alt Cancelar cadastro
    usuario -> InterfaceClientes: 3:cancelarCadastro()
    InterfaceClientes --> usuario: 3.1:retornarParaAbaClientes()

else Continuar cadastro
    usuario -> InterfaceClientes: 3:informarDadosCliente(nome, telefone, preferencias)
    usuario -> InterfaceClientes: 4:salvarCliente()

    InterfaceClientes -> GestaoService: 4.1:cadastrarCliente(dados)
    activate GestaoService

    GestaoService -> Cliente: 4.1.1:validarDados(nome, telefone, preferencias)
    Cliente --> GestaoService

    alt Nome não preenchido
        GestaoService --> InterfaceClientes: 4.1.2:erro("Preencha este campo")
        InterfaceClientes --> usuario: 4.1.3:exibirMensagemErro()

    else Dados válidos
        GestaoService -> Cliente: 4.1.2:criarCliente(nome, telefone, preferencias)
        Cliente --> GestaoService: cliente

        GestaoService --> InterfaceClientes: 4.1.3:clienteCadastrado(cliente)
        InterfaceClientes --> usuario: 4.1.4:exibirMensagemSucesso()
    end

    deactivate GestaoService
end

deactivate InterfaceClientes

@enduml