@startuml
left to right direction

class Usuario{
    id
    nome 
    email
    senha
    tipo_usuario 
    ativo 
    autenticar()
    ehGerente()
}

class Cliente{
    telefone
    preferencias
    dataCadastro 
}

class GestaoService{
    cadastrarUsuario()
    removerUsuario()
    listarUsuarios()
    cadastrarCliente()
    buscarCliente()
    obterHistoricoCliente()
}

class Agendamento{
    id
    clientId
    profissionalId
    dataHora
    tipoServico
    status
    valor
    tipoPagamento
    horaInicio
    observacoes
    reagendar()
    cancelar()
    finalizar()
    conflita()
}
@enduml